  server:
    port: 46005

  spring:
    temporal:
      start-workers: true
      connection:
        target: local
        #target.namespace: ${TEMPORAL_NAMESPACE}
      workers:
        - task-queue: TEST_QUEUE
          capacity:
            max-concurrent-workflow-task-executors: 10
            max-concurrent-activity-executors: 10
            max-concurrent-workflow-task-pollers: 5
            max-concurrent-activity-task-pollers: 5
      workflow-cache:
        max-instances: 10
        max-threads: 10
      workersAutoDiscovery:
        packages: com.example.temporalautoconfigure
      timeouts:
        #activityStartToCloseTimeout: 100
        #workflowTimeout: 100